-- Generated by Yueyue
-- Main App
addappid(2528800)
-- Manifests
addappid(2528802, 1, "93fd73f8e84c6bbec78cbadc1ca81e1ac754d8c5fe20167829704944fae17156")
setManifestid(2528802, "1236267771441634497")
