-- Generated by SteamAppDumper (Author:pjy612)
-- Extracted by 影游仙人
addappid(3947480)
addappid(3947481,0,"daf64a65a6b9d2a679534c4b1e1eff158f5caab7258b822a607da82c80d28569")
--setManifestid(3947481,"926157918895481550")