-- Generated by Yueyue
-- Main App
addappid(664120)
-- Manifests
addappid(664122, 1, "eb8b80bfe07fd9443252f5657cf14bd5e96d8e9e3b9ea02493e48e8dc0dc1a96")
setManifestid(664122, "535936973420779585")
